<main class="d-flex flex-column">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb m-0">
        <li class="breadcrumb-item">Administration</li>
        <li class="breadcrumb-item active" aria-current="page">Gestion des articles</li>
    </ol>
  </nav>
  <div class="flex-grow-1 d-md-flex align-items-stretch">
    <?php include 'admin_menu.phtml'; ?>
    <section class="col-md-7 py-4 mx-auto">
      <header class="jumbotron text-center">
        <h2 class="text-center mb-4 display-4">Gestion des articles</h2>
        <hr class="my-4">
        <a class="btn btn-dark" href="https://sql.sh/cours/insert-into" target="_blank"><i class="fa fa-external-link-alt" aria-hidden="true"></i> SQL INSERT INTO</a>
        <a class="btn btn-dark" href="https://sql.sh/cours/update" target="_blank"><i class="fa fa-external-link-alt" aria-hidden="true"></i> SQL UPDATE</a>
        <a class="btn btn-dark" href="https://sql.sh/cours/delete" target="_blank"><i class="fa fa-external-link-alt" aria-hidden="true"></i> SQL DELETE</a>
        <a class="btn btn-dark" href="https://www.php.net/manual/fr/pdostatement.rowcount.php" target="_blank"><i class="fa fa-external-link-alt" aria-hidden="true"></i> Nombre de lignes affectées par une requête</a>
      </header>
      <nav class="mb-4">
        <a class="btn btn-primary" href="admin_posts_new.php">
          <i class="fas fa-plus" aria-hidden="true"></i>
          Créer un article
        </a>
      </nav>
      <table class="table table-striped">
        <caption>
          Liste des posts classés par ordre chronologique inversé
          <strong>(<?= $countPost ?> articles au total)</strong>
        </caption>
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>Création</th>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($posts as $post): ?>
          <tr>
            <td>
              <?= htmlspecialchars( $post['Id'] ); ?>
            </td>
            <td>
              <?= htmlspecialchars( $post['DateMaj'] ); ?>
            </td>
            <td>
              <a
                href="show_post.php?id=<?= intval( $post['Id'] ) ?>">
                <?= htmlspecialchars( $post['Title'] ); ?>
              </a>
            </td>
            <td>
              <?= htmlspecialchars( $post['FirstName'] ); ?>
              <?= htmlspecialchars( $post['LastName'] ); ?>
            </td>
            <td>
              <?= htmlspecialchars( $post['Name'] ); ?>
            </td>
            <td>
              <a
                class="btn btn-warning"
                title="Modifier le post"
                href="admin_posts_edit.php?id=<?= intval( $post['Id'] ); ?>">
                <i class="fa fa-pen-nib" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <a
                href="admin_posts_delete.php?id=<?= intval( $post['Id'] ); ?>"
                class="btn btn-danger"
                title="Supprimer le post">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
              <button
                type="button"
                class="btn btn-warning"
                title="Supprimer le post"
                data-toggle="modal"
                data-target="#modal-delete-<?= intval( $post['Id'] ); ?>">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </button>
              <div id="modal-delete-<?= intval( $post['Id'] ); ?>" class="modal fade" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Supprimer l'article</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>Êtes-vous sûr de vouloir supprimer cet article ?</p>
                    </div>
                    <div class="modal-footer">
                      <a
                        class="btn btn-danger btn-lg"
                        title="Supprimer le post"
                        href="admin_posts_delete.php?id=<?= intval( $post['Id'] ); ?>">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      </a>
                      <a
                        class="btn btn-dark btn-lg"
                        data-dismiss="modal"
                        title="J'abandonne !"
                        href="admin_posts_index.php">
                        <i class="fa fa-hand-paper" aria-hidden="true"></i>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </section>
  </div>
</main>
